import sdk, {
  Device,
  DeviceCreator,
  DeviceCreatorSettings,
  DeviceProvider,
  ScryptedDeviceBase,
  ScryptedDeviceType,
  ScryptedInterface,
  ScryptedNativeId,
  Setting,
  SettingValue,
  Settings,
} from "@scrypted/sdk";
import { AqaraCamera } from "./camera";

const { deviceManager } = sdk;

export class AqaraProvider
  extends ScryptedDeviceBase
  implements DeviceProvider, DeviceCreator, Settings
{
  private cameras = new Map<string, AqaraCamera>();

  constructor(nativeId?: string) {
    super(nativeId);
  }

  async getSettings(): Promise<Setting[]> {
    return [
      {
        key: "info",
        title: "About",
        readonly: true,
        value:
          "Add an Aqara camera below. Enable 'RTSP LAN Preview' in the Aqara Home app for each camera and note the generated username and password.",
      },
    ];
  }

  async putSetting(_key: string, _value: SettingValue): Promise<void> {
    // no-op: plugin-wide settings are all per-camera today
  }

  async getCreateDeviceSettings(): Promise<Setting[]> {
    return [
      {
        key: "name",
        title: "Name",
        description: "Friendly name shown in Scrypted (e.g. Front Door).",
        placeholder: "Front Door",
      },
      {
        key: "host",
        title: "IP Address or Hostname",
        description: "The camera's LAN IP address.",
        placeholder: "192.168.1.50",
      },
      {
        key: "username",
        title: "RTSP Username",
        description:
          "Generated by the Aqara Home app when 'RTSP LAN Preview' is enabled.",
      },
      {
        key: "password",
        title: "RTSP Password",
        type: "password",
        description:
          "Generated by the Aqara Home app when 'RTSP LAN Preview' is enabled.",
      },
      {
        key: "isDoorbell",
        title: "Is a Doorbell",
        description:
          "Enable if this camera has a doorbell button (G410, G4, etc.).",
        type: "boolean",
        value: true,
      },
    ];
  }

  async createDevice(settings: DeviceCreatorSettings): Promise<string> {
    const name = String(settings.name || "Aqara Camera").trim();
    const host = String(settings.host || "").trim();
    const username = String(settings.username || "").trim();
    const password = String(settings.password || "");
    const isDoorbell = settings.isDoorbell === true || settings.isDoorbell === "true";

    if (!host) {
      throw new Error("IP Address is required");
    }

    const nativeId = `aqara-${Date.now().toString(36)}-${Math.random()
      .toString(36)
      .slice(2, 8)}`;

    const interfaces: ScryptedInterface[] = [
      ScryptedInterface.VideoCamera,
      ScryptedInterface.MotionSensor,
      ScryptedInterface.Settings,
      ScryptedInterface.Online,
    ];
    if (isDoorbell) {
      interfaces.push(ScryptedInterface.BinarySensor);
    }

    const device: Device = {
      nativeId,
      name,
      type: isDoorbell ? ScryptedDeviceType.Doorbell : ScryptedDeviceType.Camera,
      interfaces,
      info: {
        manufacturer: "Aqara",
        model: isDoorbell ? "G410 (or compatible)" : "Aqara Camera",
      },
    };

    await deviceManager.onDeviceDiscovered(device);

    // Persist configuration into the child device's storage via the manager.
    const storage = deviceManager.getDeviceStorage(nativeId);
    storage.setItem("host", host);
    storage.setItem("username", username);
    storage.setItem("password", password);
    storage.setItem("isDoorbell", String(isDoorbell));
    storage.setItem("mainChannel", "ch1");
    storage.setItem("subChannel", "ch3");
    storage.setItem("rtspPort", "8554");

    return nativeId;
  }

  async getDevice(nativeId: ScryptedNativeId): Promise<AqaraCamera> {
    if (!nativeId) {
      throw new Error("Missing nativeId");
    }
    let camera = this.cameras.get(nativeId);
    if (!camera) {
      camera = new AqaraCamera(nativeId);
      this.cameras.set(nativeId, camera);
    }
    return camera;
  }

  async releaseDevice(id: string, nativeId: ScryptedNativeId): Promise<void> {
    if (nativeId) {
      const camera = this.cameras.get(nativeId);
      camera?.release();
      this.cameras.delete(nativeId);
    }
  }
}
