import sdk, {
  Device,
  DeviceCreator,
  DeviceCreatorSettings,
  DeviceProvider,
  ScryptedDeviceBase,
  ScryptedDeviceType,
  ScryptedInterface,
  ScryptedNativeId,
  Setting,
  SettingValue,
  Settings,
} from "@scrypted/sdk";
import { AqaraCamera } from "./camera";

const { deviceManager } = sdk;

export class AqaraProvider
  extends ScryptedDeviceBase
  implements DeviceProvider, DeviceCreator, Settings
{
  private cameras = new Map<string, AqaraCamera>();

  constructor(nativeId?: string) {
    super(nativeId);
    void this.resyncDevices();
  }

  /**
   * Re-announce existing cameras on plugin startup so Scrypted picks up any
   * change to the declared interfaces (e.g. BinarySensor was removed in
   * 0.2.x). Without this, devices created by older plugin versions keep
   * stale interface declarations and stuck sensor state.
   */
  private async resyncDevices(): Promise<void> {
    try {
      const nativeIds = deviceManager.getNativeIds();
      for (const nid of nativeIds) {
        if (!nid) continue;
        const storage = deviceManager.getDeviceStorage(nid);
        if (!storage.getItem("host")) continue; // not one of ours

        await deviceManager.onDeviceDiscovered({
          nativeId: nid,
          name: storage.getItem("name") || "Aqara Camera",
          type: ScryptedDeviceType.Camera,
          interfaces: [
            ScryptedInterface.VideoCamera,
            ScryptedInterface.Settings,
            ScryptedInterface.Online,
          ],
          info: {
            manufacturer: "Aqara",
            model: "Aqara Camera",
          },
        });
      }
    } catch (err) {
      this.console.error("Failed to resync devices:", err);
    }
  }

  async getSettings(): Promise<Setting[]> {
    return [
      {
        key: "info",
        title: "About",
        readonly: true,
        value:
          "Add an Aqara camera below. Enable 'RTSP LAN Preview' in the Aqara Home app for each camera and note the generated username and password.",
      },
    ];
  }

  async putSetting(_key: string, _value: SettingValue): Promise<void> {
    // no-op: plugin-wide settings are all per-camera today
  }

  async getCreateDeviceSettings(): Promise<Setting[]> {
    return [
      {
        key: "name",
        title: "Name",
        description: "Friendly name shown in Scrypted (e.g. Front Door).",
        placeholder: "Front Door",
      },
      {
        key: "host",
        title: "IP Address or Hostname",
        description: "The camera's LAN IP address.",
        placeholder: "192.168.1.50",
      },
      {
        key: "username",
        title: "RTSP Username",
        description:
          "Generated by the Aqara Home app when 'RTSP LAN Preview' is enabled.",
      },
      {
        key: "password",
        title: "RTSP Password",
        type: "password",
        description:
          "Generated by the Aqara Home app when 'RTSP LAN Preview' is enabled.",
      },
    ];
  }

  async createDevice(settings: DeviceCreatorSettings): Promise<string> {
    const name = String(settings.name || "Aqara Camera").trim();
    const host = String(settings.host || "").trim();
    const username = String(settings.username || "").trim();
    const password = String(settings.password || "");

    if (!host) {
      throw new Error("IP Address is required");
    }

    const nativeId = `aqara-${Date.now().toString(36)}-${Math.random()
      .toString(36)
      .slice(2, 8)}`;

    const device: Device = {
      nativeId,
      name,
      type: ScryptedDeviceType.Camera,
      interfaces: [
        ScryptedInterface.VideoCamera,
        ScryptedInterface.Settings,
        ScryptedInterface.Online,
      ],
      info: {
        manufacturer: "Aqara",
        model: "Aqara Camera",
      },
    };

    // Persist configuration BEFORE announcing the device, so the camera's
    // constructor sees the host/creds when Scrypted calls getDevice().
    const storage = deviceManager.getDeviceStorage(nativeId);
    storage.setItem("name", name);
    storage.setItem("host", host);
    storage.setItem("username", username);
    storage.setItem("password", password);
    storage.setItem("mainChannel", "ch1");
    storage.setItem("subChannel", "ch3");
    storage.setItem("rtspPort", "8554");

    await deviceManager.onDeviceDiscovered(device);

    return nativeId;
  }

  async getDevice(nativeId: ScryptedNativeId): Promise<AqaraCamera> {
    if (!nativeId) {
      throw new Error("Missing nativeId");
    }
    let camera = this.cameras.get(nativeId);
    if (!camera) {
      camera = new AqaraCamera(nativeId);
      this.cameras.set(nativeId, camera);
    }
    return camera;
  }

  async releaseDevice(id: string, nativeId: ScryptedNativeId): Promise<void> {
    if (nativeId) {
      const camera = this.cameras.get(nativeId);
      camera?.release();
      this.cameras.delete(nativeId);
    }
  }
}
