import sdk, {
    Device,
    Setting,
    Settings,
    SettingValue,
    DeviceCreator,
    DeviceProvider,
    ScryptedNativeId,
    ScryptedInterface,
    ScryptedDeviceBase,
    ScryptedDeviceType,
    DeviceCreatorSettings
} from '@scrypted/sdk';

import { AqaraCamera } from './camera';

const { deviceManager } = sdk;

const AQARA_DEVICE_INFO = {
    manufacturer: 'Aqara',
    model: 'Aqara Camera'
} as const;

const AQARA_CAMERA_INTERFACES = [
    ScryptedInterface.VideoCamera,
    ScryptedInterface.Settings,
    ScryptedInterface.Online,
    ScryptedInterface.Intercom,
    ScryptedInterface.BinarySensor,
    ScryptedInterface.HttpRequestHandler
] as const;

class AqaraProvider extends ScryptedDeviceBase implements DeviceCreator, DeviceProvider, Settings {
    private readonly cameras = new Map<string, AqaraCamera>();

    constructor(nativeId?: string) {
        super(nativeId);
        void this.resyncDevices();
    }

    async createDevice(settings: DeviceCreatorSettings): Promise<string> {
        const name = String(settings.name || 'Aqara Camera').trim();
        const host = String(settings.host || '').trim();
        const username = String(settings.username || '').trim();
        const password = String(settings.password || '');

        if (!host) {
            throw new Error('IP Address is required');
        }

        const nativeId = `aqara-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;

        const device: Device = {
            name,
            nativeId,
            info: AQARA_DEVICE_INFO,
            type: ScryptedDeviceType.Doorbell,
            interfaces: [...AQARA_CAMERA_INTERFACES]
        };

        // Persist configuration BEFORE announcing the device, so the camera's
        // constructor sees the host/creds when Scrypted calls getDevice().
        const storage = deviceManager.getDeviceStorage(nativeId);
        storage.setItem('name', name);
        storage.setItem('host', host);
        storage.setItem('username', username);
        storage.setItem('password', password);
        storage.setItem('mainChannel', 'ch1');
        storage.setItem('subChannel', 'ch3');
        storage.setItem('rtspPort', '8554');

        await deviceManager.onDeviceDiscovered(device);

        return nativeId;
    }

    async getCreateDeviceSettings(): Promise<Setting[]> {
        return [
            {
                key: 'name',
                title: 'Name',
                placeholder: 'Front Door',
                description: 'Friendly name shown in Scrypted (e.g. Front Door).'
            },
            {
                key: 'host',
                placeholder: '192.168.1.50',
                title: 'IP Address or Hostname',
                description: "The camera's LAN IP address."
            },
            {
                key: 'username',
                title: 'RTSP Username',
                description: "Generated by the Aqara Home app when 'RTSP LAN Preview' is enabled."
            },
            {
                key: 'password',
                type: 'password',
                title: 'RTSP Password',
                description: "Generated by the Aqara Home app when 'RTSP LAN Preview' is enabled."
            }
        ];
    }

    async getDevice(nativeId: ScryptedNativeId): Promise<AqaraCamera> {
        if (!nativeId) {
            throw new Error('Missing nativeId');
        }
        let camera = this.cameras.get(nativeId);
        if (!camera) {
            camera = new AqaraCamera(nativeId);
            this.cameras.set(nativeId, camera);
        }
        return camera;
    }

    async getSettings(): Promise<Setting[]> {
        return [
            {
                key: 'info',
                title: 'About',
                readonly: true,
                value: "Add an Aqara camera below. Enable 'RTSP LAN Preview' in the Aqara Home app for each camera and note the generated username and password."
            }
        ];
    }

    async putSetting(_key: string, _value: SettingValue): Promise<void> {
        // no-op: plugin-wide settings are all per-camera today
    }

    async releaseDevice(id: string, nativeId: ScryptedNativeId): Promise<void> {
        if (nativeId) {
            const camera = this.cameras.get(nativeId);
            camera?.release();
            this.cameras.delete(nativeId);
        }
    }

    /**
     * Re-announce existing cameras on plugin startup so Scrypted picks up any
     * change to the declared interfaces (e.g. BinarySensor was removed in
     * 0.2.x). Without this, devices created by older plugin versions keep
     * stale interface declarations and stuck sensor state.
     */
    private async resyncDevices(): Promise<void> {
        try {
            const nativeIds = deviceManager.getNativeIds();
            for (const nid of nativeIds) {
                if (!nid) continue;
                const storage = deviceManager.getDeviceStorage(nid);
                if (!storage.getItem('host')) continue; // not one of ours

                await deviceManager.onDeviceDiscovered({
                    nativeId: nid,
                    info: AQARA_DEVICE_INFO,
                    type: ScryptedDeviceType.Doorbell,
                    interfaces: [...AQARA_CAMERA_INTERFACES],
                    name: storage.getItem('name') || 'Aqara Camera'
                });
            }
        } catch (err) {
            this.console.error('Failed to resync devices:', err);
        }
    }
}

export { AqaraProvider };
